version: '3'

services:
  vcache_mgr:
    image: vcache-mgr
    build:
      context: ./docker-context/node-red
    container_name: vcache_mgr
    hostname: ${VCACHE_HOSTNAME}
    volumes:
      - "./mgmt-data:/data"
      - "./run:/var/run"
      - "./salt:/srv/salt"
    ports:
      - "4505:4505"
      - "4506:4506"
      - "1880:1880"     # close this for production
    pid: shareable
    restart: always
    depends_on:
      - vcache_mgr_redis

  vcache_mgr_redis:
    image: redis:latest
    container_name: vcache_mgr_redis
    volumes:
      - "redis_data:/data"
    networks:
      - vcache_mgr_net
    # close this for production
    ports:
      - "6380:6379"
    restart: always

volumes:
  redis_data:
    name: vcache_mgr_redis_data

networks:
  vcache_mgr_net:
    name: vcache_mgr_net
    driver: bridge
    enable_ipv6: false
